exclude: [build.bat, README.md, inuit.css, style.scss, node_modules, Gruntfile.js, tasks, package.json]
markdown: rdiscount
highlighter: true
paginate: 4
permalink: /post/:year/:month/:title
gems:
  - jekyll-redirect-from


name: Wayne Moir
description: A user experience designer that occasionally writes about interesting things.
url: http://www.waynemoir.com