exclude: [build.bat, README.md, inuit.css, style.scss, node_modules, Gruntfile.js, tasks, package.json]
markdown: rdiscount
pygments: true
permalink: /articles/:year/:month/:title

name: Wayne Moir
description: A user experience designer that occasionally writes about interesting things.
url: http://www.waynemoir.com