exclude: [build.bat, README.md, inuit.css, style.scss, node_modules, Gruntfile.js, tasks]
markdown: rdiscount
pygments: true
permalink: /articles/:year/:month/:title

name: Wayne Moir
description: An experience designer that occasionally writes about things.
url: http://www.waynemoir.com